/* eslint-disable */
export default {
    papersList: [{
            id: '1',
            title: "Tube Wall Plasticity Behaviour and Strengthening o f Hollow Sectional Tubes",
            author: "M. S. Anagha, Anjal Santhosh",
            submissionYearMonth: "",
            pages: "01-08",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/de4e8466-862f-4a00-9179-348425d121d6/ICICMCT_23_IJIRE_V4+I3_1_01-06.pdf",
            show: false,
        },
        {
            id: '2',
            title: "Flood Prediction and Susceptibility Mapping of Chalakudy Tehsil Using ARCGIS",
            author: "Ansaf Rasheed, Adhitya M S, Georgy C S, Goury Lakshmi",
            submissionYearMonth: "",
            pages: "09-29",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/e1e2089a-c97f-4e1e-aa22-6285187af67d/ICICMCT_23_IJIRE_V4+I3_2_07-15.pdf",
            show: false,
        },
        {
            id: '3',
            title: "Greywater Treatment Technique Using Fruit Peels",
            author: "Arya. C, Gopu Surjith, Hana P Basheer, Indrajith.J. S, Dr Anjali P Sasidharan",
            submissionYearMonth: "",
            pages: "30-34",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/b6cc5678-ba21-482d-a07e-53a3fe1e2589/ICICMCT_23_IJIRE_V4+I3_3_16-21.pdf",
            show: false,
        },
        {
            id: '4',
            title: "Development of Optimum Lightweight Cold-Formed Steel Composite Built-Up Beams",
            author: "Fathima R.M, Nisha Varghese",
            submissionYearMonth: "",
            pages: "35-43",
            articleType: "Original Article",
            doi: ".",
            abstract: "Oil Pollution is the resultant contamination of environment due to the presence of oil in excessive quantity. Oil contamination is a genuine danger to our environment and biological community and should be controlled with urgency. The oil contamination is influencing the geotechnical properties of soil. So, it’s a need to study the effect of diesel oil on geotechnical properties of soils. In this study, the variation of geotechnical properties like Atterberg limits and unconfined compressive strength with the addition of diesel oil in clay was considered. For Removal of Contaminated oil adding EDTA at thrice the oil content. After removal of oil content further adding glass fiber for the strength characteristics. The results showed that increase in the amount of diesel oil decreases the Atterberg limits and unconfined compressive strength. Increasing diesel oil content will leads to decrease in strength and settlement. For that EDTA was best remedial measures for removing oil content\n keyWord:Oil pollution, geotechnical properties, Atterberg limits, unconfined compressive strength, diesel oil. EDTA, Glass fiber.\nReferences\n1)Anele,OmasirichiDepartmentofCivilEngineeringRiversStateUniversityofScience&TechnologyNkpolu,PortHarcourt,Nigeria,October2015,EFFECT OF WASTE ENGINE OIL CONTAMINATION ON GEOTECHNICAL PROPERTIES OF CLAY SOIL. Jan.2019, Vol.16, Issue 53, pp.32-39\n 2) M.O.Karkush Civil Engineering, Baghdad University, Iraq A.T.Zaboon Construction and Building Department, University of Technology, Iraq H.M.Hussien Civil Engineering, Baghdad University, Iraq, March2012 Studying the effects of contamination on the geotechnical properties of clayey soil\n 3) FayazAhamedAP1,ESahad2,Mohammed NishmalK3,Mohamed MusfarKP4,Chidanand Naik 5May2019,Study on the Geotechnical Characteristics of Contaminated Soil\n 4) TharaRDas1,TwinkleVinu2,November2017, Strength Characteristics of Diesel Oil Contaminated Marine Clay\n 5) PrasannaG1, Shimna Manoharan2July2016, A Review on Effect of Crude Oil on the Geotechnical Properties of Soil.\n 6) HerbertE.Allen*andPing=HsienChen DepartmentofCivilEngineering,UniversityofDelaware,Newark,DE19716,Nov2012,Remediation of Metal Contaminated Soil by EDTA Incorporating Electro chemical Recovery of Metal and EDTA",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/5e1d0d08-f18e-4c96-90bf-48f4c386a4a7/ICICMCT_23_IJIRE_V4+I3_4_22-27.pdf",
            show: false,
        },
        {
            id: '5',
            title: "Flexural Behaviour of Hybrid Double-Skin Tubular Beams Having Perfobond Hoop Shear Connectors",
            author: "Jenitta C S, Ardra P Nair",
            submissionYearMonth: "",
            pages: "44-50",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/836930ec-f224-4517-95fe-1db01cbb9f20/ICICMCT_23_IJIRE_V4+I3_5_28-32.pdf",
            show: false,
        },
        {
            id: '6',
            title: "Study on Concrete Filled Steel Tube Columns Reinforced with Diagonal Stiffener",
            author: "Muhammed Suhail A S, Kiran Babu A R",
            submissionYearMonth: "",
            pages: "51-54",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/89111015-6a38-4b2b-b680-a8b861f287d0/ICICMCT_23_IJIRE_V4+I3_6_33-38.pdf",
            show: false,
        },
        {
            id: '7',
            title: "Seismic Analysis of an Optimised Energy Dissipating Shear Key",
            author: "Nizwin K S, Anju Mary Ealias",
            submissionYearMonth: "",
            pages: "55-62",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/379b6b82-ed4a-47eb-820a-831278ce827b/ICICMCT_23_IJIRE_V4+I3_7_39-44.pdf",
            show: false,
        },
        {
            id: '8',
            title: "Experimental and Analytical Investigation on Strengthening of Cutout in a Composite Slab",
            author: "Prince Kesav, Dr Abhilasha P.S.",
            submissionYearMonth: "",
            pages: "63-70",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/84448ef0-76bd-4575-a117-9da5ccc20db7/ICICMCT_23_IJIRE_V4+I3_8_45-52.pdf",
            show: false,
        },
        {
            id: '9',
            title: "Overtaking Conflict Analysis and Risk Modeling for Undivided Two-Lane Road Section",
            author: "Akshaya V Kumar, Dr. Sheela Alex",
            submissionYearMonth: "",
            pages: "71-78",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/7b33b379-46d7-48a7-9a87-4fa01ddd4751/ICICMCT_23_IJIRE_V4+I3_9_53-56.pdf",
            show: false,
        },
        {
            id: '10',
            title: "Study of The Effect of Fiber Type and Volume Variation on High Performance Concrete",
            author: "Ashrin Saira Paul, Anju Paul, Dr. Elson John",
            submissionYearMonth: "",
            pages: "79-83",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/1c8fb4f8-8551-4460-854e-f126804c4c83/ICICMCT_23_IJIRE_V4+I3_10_57-60.pdf",
            show: false,
        },
        {
            id: '11',
            title: "Water Analysis and Forward Osmosis",
            author: "Shereena N.P , Dr. Noel Jacob Kaleekkal, Fouad Ebn Muhammad Abdulla ",
            submissionYearMonth: "",
            pages: "84-95",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/0a46f135-5269-45d2-88c9-7512b3f40f5d/ICICMCT_23_IJIRE_V4+I3_11_61-64.pdf",
            show: false,
        },
        {
            id: '12',
            title: "Axial Performance of GFRP Wrapped Partially Encased Composite Column with Corrugated Web",
            author: "Sijin Varghese, Dr Abhilasha P. S",
            submissionYearMonth: "",
            pages: "96-101",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/c89ccd2e-2cd2-4208-ac8c-89f32fee02c1/ICICMCT_23_IJIRE_V4+I3_12_65-68.pdf",
            show: false,
        },
        {
            id: '13',
            title: "Axial and Bending Performance of Spiral Stiffened Thin Walled CFDST Column",
            author: "K.S. Siya, E. K. Amritha",
            submissionYearMonth: "",
            pages: "102-109",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/b824383d-1b66-47d1-ae9b-49e666f34b1a/ICICMCT_23_IJIRE_V4+I3_13_69-76.pdf",
            show: false,
        },
        {
            id: '14',
            title: "Efficacy of Activated Carbon in Removing Sulphate and Chloride from Sea Water",
            author: "Navaz K A, Rudhira M R, Saranya V M, Sneha M S, Dr Anjali P Sasidharan",
            submissionYearMonth: "",
            pages: "110-114",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/22763984-3e0b-4e47-9013-85d3b3354c5c/ICICMCT_23_IJIRE_V4+I3_14_77-81.pdf",
            show: false,
        },
        {
            id: '15',
            title: "Strengthening of fibre reinforced concrete columns using high strength concrete filled steel tubes",
            author: "Sreelakshmi Saji, Nisha Varghese",
            submissionYearMonth: "",
            pages: "115-121",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/22763984-3e0b-4e47-9013-85d3b3354c5c/ICICMCT_23_IJIRE_V4+I3_14_77-81.pdf",
            show: false,
        },
        {
            id: '16',
            title: "Structural Analysis and Design of Tall Building and Validation Using IS 16700 (2023)",
            author: "Sreerag C S , Sreelakshmi C , Sidharth P , Jofna Joy , Ajayakumar V T",
            submissionYearMonth: "",
            pages: "110-114",
            articleType: "Original Article",
            doi: ".",
            paperUrl: "https://fdrpjournals.s3.ap-south-1.amazonaws.com/main/1/archives/22763984-3e0b-4e47-9013-85d3b3354c5c/ICICMCT_23_IJIRE_V4+I3_14_77-81.pdf",
            show: false,
        },
    ],
}
